### ISSUE TITLE
[fp16 error] In GPT-2 run example 

### ISSUE THREAD

**Issue by lin88lin8850** [HPDL-Group/Merak#2]
when I set fp16=true during training gpt-2, error happens:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/26682403/205259033-babded66-9475-40d1-90ef-10c38d6e0818.png">

**Comment by TXacs** [comment]
This error reports from the gpt2 model of transformers. Because the `reorder_and_upcast_attn` set `True` in [config](https://github.com/huggingface/transformers/blob/6c1a0b393101613feea4319684925350848a0274/src/transformers/models/gpt2/modeling_gpt2.py#L261).

**Comment by TXacs** [comment]
This error come from the gpt2 model of transformers. Because the reorder_and_upcast_attn set True in [config](https://github.com/huggingface/transformers/blob/6c1a0b393101613feea4319684925350848a0274/src/transformers/models/gpt2/modeling_gpt2.py#L261).

**Comment by lin88lin8850** [comment]
thanks a lot! bug solved, the issue will be closed
